### ISSUE TITLE
MatcherFactory Broken with ezplatform v3

### ISSUE THREAD

**Issue by wizhippo** [netgen/ezplatform-site#135]
MatcherFactory extends a `final` class and throws error

Introduced by updstream https://github.com/ezsystems/ezpublish-kernel/commit/177d87da3cec7dc2bf070c130ce95552479a9f04

**Comment by emodric** [comment]
Yep, known issue. There's also couple of more issues to fix.

I think @pspanja is on it :)

**Comment by pspanja** [comment]
Thanks for reporting, I'll try to fix this one today.
