### ISSUE TITLE
Problem on controller content preview override 

### ISSUE THREAD

**Issue by YohannsMonnier** [netgen/ezplatform-site#167]
The alias for ezpublish.controller.content.preview must indicate that this service is public, as it is in the overrided definition

**Comment by emodric** [comment]
@YohannsMonnier Hm, probably issue with https://github.com/netgen/ezplatform-site-api/blob/4.0/bundle/DependencyInjection/Compiler/PreviewControllerOverridePass.php#L36

Can you test if removing that line helps? If it does, we can just remove it here too since 4.0 does not support legacy anyway.
