### ISSUE TITLE
Make bundle compatible with sensio/framework-extra-bundle ^6.0

### ISSUE THREAD

**Issue by rembertin** [netgen/ezplatform-site#204]
Currently, the bundle requires `sensio/framework-extra-bundle` at version `^5.5`.
The problem is that since its version `3.3.6`, the package [ibexa/oss](https://packagist.org/packages/ibexa/oss) requires `sensio/framework-extra-bundle` at version `^6.1.0`.
So currently it's not possible to install `netgen/ezplatform-site-api` with the last version of Ibexa DXP.

Could it be possible to require `sensio/framework-extra-bundle` either at version `^5.5` and `^6.0`? (in composer.json: `"sensio/framework-extra-bundle": "^5.5|^6.0"`).

Thanks in advance.

**Comment by pspanja** [comment]
Hi @rembertin, thanks for the report. I’m on vacation ATM, so will look into it in the next couple of weeks.

**Comment by rembertin** [comment]
Hi, thanks for your answer. I created a PR for this if it can make your life easier. => #205
Have a nice vacation!

**Comment by pspanja** [comment]
Fixed in #205
