### ISSUE TITLE
PagerFanta adapters and facets

### ISSUE THREAD

**Issue by wizhippo** [netgen/ezplatform-site#72]
As pagerfanta only returns a slice there is no access to the facets.

Any change of adding to the adapters a method such as  found in the SolariumAdapter?

https://github.com/shieldo/Pagerfanta/blob/f9d663b8ac9481baf5cd7253e31d7977b443e8a8/src/Pagerfanta/Adapter/SolariumAdapter.php#L111

Perhaps a getSearchResult() method?

**Comment by pspanja** [comment]
That makes sense, not only for facets, but for max score as well (ping @hknezevic)
I'll add it as time permits. And we also accept contributions :)

**Comment by wizhippo** [comment]
See https://github.com/netgen/ezplatform-site-api/pull/74
